"""Add TrackedEntity and Device

Revision ID: 30f9468a59fc
Revises:
Create Date: 2024-08-25 01:50:57.429891

"""
import sqlmodel # type: ignore
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f9468a59fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trackedentity',
    sa.Column('name', sa.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trackedentity_name'), 'trackedentity', ['name'], unique=True)
    op.create_table('device',
    sa.Column('name', sa.AutoString(), nullable=False),
    sa.Column('mac', sa.AutoString(), nullable=False),
    sa.Column('trackedentity_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trackedentity_id'], ['trackedentity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_mac'), 'device', ['mac'], unique=True)
    op.create_index(op.f('ix_device_name'), 'device', ['name'], unique=False)
    op.create_index(op.f('ix_device_trackedentity_id'), 'device', ['trackedentity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_trackedentity_id'), table_name='device')
    op.drop_index(op.f('ix_device_name'), table_name='device')
    op.drop_index(op.f('ix_device_mac'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_trackedentity_name'), table_name='trackedentity')
    op.drop_table('trackedentity')
    # ### end Alembic commands ###
