name: Tests

on:
    - push
    - pull_request

permissions:
    contents: read

jobs:
    test:
        runs-on: self-hosted
        steps:
            - name: Test with unittest
              run: python3 -m unittest