name: Tests

on:
    - push
    - pull_request

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout commit
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip setuptools wheel
                pip install -r requirements.txt
            - name: Test with unittest
              run: python -m unittest
