name: Tests

on:
    - push
    - pull_request

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Test with unittest
              run: python3 -m unittest
